#!/bin/sh

if [ $# -ne 1 ]; then
    echo "usage: $0 <logdir>"
    exit 1
fi

num_nodes="$(find "$1" -type f -name '*.load' | wc -l)"
echo "Total nodes: $num_nodes"
for data_file in "$1"/*.load; do
    node_id="$(basename "$data_file" | cut -c8-9)"
    plot_file="w${node_id}n$(printf "%02d" "$num_nodes").png"
    echo "Plotting $data_file into $plot_file"
    ./plot-cpu-usage.sh "$data_file" "$plot_file"
done
